version: '3'

services:

 nginx:
  build: ./nginx
  ports:
   - "8080:80"
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   - ./nginx/html:/usr/share/nginx/html
  networks:
   - docker_elk
  depends_on:
   - logstash

 elasticsearch:
  build: ./elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"
  environment:
   ES_JAVA_OPTS: "-Xmx256m -Xms256m"
  user: esuser
  networks:
   - docker_elk

 logstash:
  build: ./logstash
  ports:
   - "5000:5000"
  user: lsuser
  networks:
   - docker_elk
  depends_on:
   - elasticsearch

 kibana:
  build: ./kibana
  ports:
   - "5601:5601"
  user: kbuser
  networks:
   - docker_elk
  depends_on:
   - elasticsearch

networks:
 docker_elk:
  driver: bridge